import { z } from 'zod';

const nonEmptyTextSchema = z
  .string()
  .trim()
  .min(1, 'Text must contain a non-whitespace character.');
const nonNegativeIntegerSchema = z.number().int().nonnegative();
const timestampSchema = z.iso.datetime({ offset: true });
const jsonRecordSchema = z.record(z.string(), z.json());

export const mayaEvidenceReferenceSchema = z
  .string()
  .regex(
    /^(?:historical|old|candidate):turn:(?:0|[1-9]\d*)(?::(?:event|guard-reply|message|action):(?:0|[1-9]\d*))?$/,
    'Evidence reference must identify a historical, old, or candidate turn or turn item.',
  );

export const mayaMeasurementValueSchema = z.json();

// OpenAI structured outputs reject the recursive JSON Schema generated by
// z.json() (`propertyNames` appears in its object branch). Computed Maya
// measurements are scalar today, so keep verdict-facing values scalar while
// allowing richer JSON inside the evidence packet for future measurements.
export const mayaVerdictMeasurementValueSchema = z.union([
  z.number().finite(),
  z.boolean(),
  z.null(),
]);

export const mayaEvidenceEventSchema = z
  .object({
    ref: mayaEvidenceReferenceSchema,
    timestamp: timestampSchema,
    type: nonEmptyTextSchema,
    data: jsonRecordSchema,
  })
  .strict();

export const mayaEvidenceGuardReplySchema = z
  .object({
    ref: mayaEvidenceReferenceSchema,
    timestamp: timestampSchema,
    message: nonEmptyTextSchema.nullable(),
    source: z.enum(['historical', 'simulated']),
    historicalMessage: nonEmptyTextSchema,
  })
  .strict();

export const mayaEvidenceMessageSchema = z
  .object({
    ref: mayaEvidenceReferenceSchema,
    timestamp: timestampSchema,
    text: nonEmptyTextSchema,
  })
  .strict();

export const mayaEvidenceActionSchema = z
  .object({
    ref: mayaEvidenceReferenceSchema,
    timestamp: timestampSchema,
    tool: nonEmptyTextSchema,
    input: jsonRecordSchema,
  })
  .strict();

export const mayaEvidenceTurnSchema = z
  .object({
    ref: mayaEvidenceReferenceSchema,
    turn: nonNegativeIntegerSchema,
    trigger: nonEmptyTextSchema,
    timestamp: timestampSchema,
    events: z.array(mayaEvidenceEventSchema),
    guardReplies: z.array(mayaEvidenceGuardReplySchema),
    copilotMessages: z.array(mayaEvidenceMessageSchema),
    actions: z.array(mayaEvidenceActionSchema),
    silent: z.boolean(),
    skipped: z.boolean(),
  })
  .strict();

function trajectorySchema(name: 'historical' | 'old' | 'candidate') {
  return z
    .object({
      name: z.literal(name),
      turns: z.array(mayaEvidenceTurnSchema).min(1),
    })
    .strict()
    .superRefine((trajectory, context) => {
      const seenReferences = new Set<string>();

      trajectory.turns.forEach((turn, turnIndex) => {
        const expectedTurnRef = `${name}:turn:${turn.turn}`;
        if (turn.ref !== expectedTurnRef) {
          context.addIssue({
            code: 'custom',
            path: ['turns', turnIndex, 'ref'],
            message: `Turn reference must equal ${expectedTurnRef}.`,
          });
        }

        const references = [turn.ref];
        const addItemReferences = (
          field: string,
          kind: string,
          items: readonly { readonly ref: string }[],
        ) => {
          items.forEach((item, itemIndex) => {
            const expectedItemRef = `${expectedTurnRef}:${kind}:${itemIndex}`;
            if (item.ref !== expectedItemRef) {
              context.addIssue({
                code: 'custom',
                path: ['turns', turnIndex, field, itemIndex, 'ref'],
                message: `Evidence reference must equal ${expectedItemRef}.`,
              });
            }
            references.push(item.ref);
          });
        };
        addItemReferences('events', 'event', turn.events);
        addItemReferences('guardReplies', 'guard-reply', turn.guardReplies);
        addItemReferences('copilotMessages', 'message', turn.copilotMessages);
        addItemReferences('actions', 'action', turn.actions);

        for (const reference of references) {
          if (seenReferences.has(reference)) {
            context.addIssue({
              code: 'custom',
              path: ['turns', turnIndex, 'ref'],
              message: `Duplicate evidence reference: ${reference}.`,
            });
          }
          seenReferences.add(reference);
        }
      });
    });
}

export const mayaHistoricalTrajectorySchema = trajectorySchema('historical');
export const mayaOldTrajectorySchema = trajectorySchema('old');
export const mayaCandidateTrajectorySchema = trajectorySchema('candidate');

export const mayaEvidencePacketSchema = z
  .object({
    callout: nonEmptyTextSchema,
    jobId: nonEmptyTextSchema,
    startTurn: nonNegativeIntegerSchema,
    endTurn: nonNegativeIntegerSchema,
    trajectories: z
      .object({
        historical: mayaHistoricalTrajectorySchema,
        old: mayaOldTrajectorySchema,
        candidate: mayaCandidateTrajectorySchema,
      })
      .strict(),
    warnings: z.array(nonEmptyTextSchema),
  })
  .strict()
  .superRefine((packet, context) => {
    if (packet.startTurn > packet.endTurn) {
      context.addIssue({
        code: 'custom',
        path: ['startTurn'],
        message: 'startTurn must not be after endTurn.',
      });
    }

    for (const [name, trajectory] of Object.entries(packet.trajectories)) {
      trajectory.turns.forEach((turn, index) => {
        if (turn.turn < packet.startTurn || turn.turn > packet.endTurn) {
          context.addIssue({
            code: 'custom',
            path: ['trajectories', name, 'turns', index, 'turn'],
            message: 'Evidence turn must remain inside packet bounds.',
          });
        }
      });
    }
  });

export const mayaMeasurementSchema = z
  .object({
    key: nonEmptyTextSchema,
    value: mayaMeasurementValueSchema,
    evidenceRefs: z.array(mayaEvidenceReferenceSchema),
  })
  .strict();

export const mayaMeasurementKindSchema = z.enum([
  'message_count',
  'message_timing',
  'scheduled_wake_silence',
  'action_counts',
  'flags',
  'escalations',
  'trigger_to_action_latency',
  'simulated_guard_replies',
]);

const mayaMeasurementSetSchema = z
  .array(mayaMeasurementSchema)
  .min(1)
  .superRefine((measurements, context) => {
    const seenKeys = new Set<string>();
    measurements.forEach((measurement, index) => {
      if (seenKeys.has(measurement.key)) {
        context.addIssue({
          code: 'custom',
          path: [index, 'key'],
          message: 'Measurement keys must be unique within a trajectory.',
        });
      }
      seenKeys.add(measurement.key);
    });
  });

export const mayaMeasurementsSchema = z
  .object({
    selectedKinds: z.array(mayaMeasurementKindSchema).min(1),
    trajectories: z
      .object({
        historical: mayaMeasurementSetSchema,
        old: mayaMeasurementSetSchema,
        candidate: mayaMeasurementSetSchema,
      })
      .strict(),
  })
  .strict();

export const mayaJudgeInputSchema = z
  .object({
    evidence: mayaEvidencePacketSchema,
    measurements: mayaMeasurementsSchema,
  })
  .strict()
  .superRefine((input, context) => {
    const knownReferences = new Set<string>();
    for (const trajectory of Object.values(input.evidence.trajectories)) {
      for (const turn of trajectory.turns) {
        knownReferences.add(turn.ref);
        turn.events.forEach((event) => knownReferences.add(event.ref));
        turn.guardReplies.forEach((reply) => knownReferences.add(reply.ref));
        turn.copilotMessages.forEach((message) =>
          knownReferences.add(message.ref),
        );
        turn.actions.forEach((action) => knownReferences.add(action.ref));
      }
    }

    for (const [trajectoryName, measurements] of Object.entries(
      input.measurements.trajectories,
    )) {
      measurements.forEach((measurement, measurementIndex) => {
        measurement.evidenceRefs.forEach((reference, referenceIndex) => {
          const path = [
            'measurements',
            'trajectories',
            trajectoryName,
            measurementIndex,
            'evidenceRefs',
            referenceIndex,
          ];
          if (!knownReferences.has(reference)) {
            context.addIssue({
              code: 'custom',
              path,
              message: `Unknown measurement evidence reference: ${reference}.`,
            });
          }
          if (!reference.startsWith(`${trajectoryName}:`)) {
            context.addIssue({
              code: 'custom',
              path,
              message: `Measurement evidence must use ${trajectoryName} trajectory references.`,
            });
          }
        });
      });
    }
  });

export const mayaCriterionSchema = z
  .object({
    claim: nonEmptyTextSchema,
    old_measurement: mayaVerdictMeasurementValueSchema,
    candidate_measurement: mayaVerdictMeasurementValueSchema,
    passed: z.boolean(),
    evidence: z.array(mayaEvidenceReferenceSchema).min(2),
  })
  .strict();

export const mayaVerdictSchema = z
  .object({
    fixed: z.boolean(),
    verdict: z.enum(['yes', 'no']),
    summary: nonEmptyTextSchema,
    confidence: z.number().int().min(0).max(100),
    criteria: z.array(mayaCriterionSchema).min(1),
    limitations: z.array(nonEmptyTextSchema),
  })
  .strict();

export type MayaEvidenceReference = z.infer<typeof mayaEvidenceReferenceSchema>;
export type MayaMeasurementValue = z.infer<typeof mayaMeasurementValueSchema>;
export type MayaMeasurementKind = z.infer<typeof mayaMeasurementKindSchema>;
export type MayaEvidencePacketInput = z.infer<typeof mayaEvidencePacketSchema>;
export type MayaMeasurementsInput = z.infer<typeof mayaMeasurementsSchema>;
export type MayaJudgeInput = z.infer<typeof mayaJudgeInputSchema>;
export type MayaCriterion = z.infer<typeof mayaCriterionSchema>;
export type MayaVerdict = z.infer<typeof mayaVerdictSchema>;
